name: tinycrypt
description: ported tinycrypt of C-tinycrypt
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'


dependencies:
  fixnum: ^1.0.0
  hex: ^0.2.0
  buffer:
    git: https://github.com/w-rui/buffer.git

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
